import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Twitter clone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="font-blink bg-black max-w-7xl mx-auto ">{children}</body>
    </html>
  );
}
